---
parser: "babel-eslint"

parserOptions:
  ecmaVersion: 6
  sourceType: "module"

env:
  browser: true
  es6: true
  node: true

globals:
  TweenMax: true
  riot: false
  opts: false
  dataLayer: false

# eslint rules -> 0: disable, 1: warn, 2: error
rules:
  # Possible Errors
  comma-dangle            : [0, "never"]
  no-cond-assign          : 2
  no-console              : 1
  no-constant-condition   : 2
  no-control-regex        : 2
  no-debugger             : 1
  no-dupe-args            : 2
  no-dupe-keys            : 2
  no-duplicate-case       : 2
  no-empty-character-class: 2
  no-empty                : 2
  no-ex-assign            : 2
  no-extra-boolean-cast   : 2
  no-extra-parens         : 1
  no-extra-semi           : 2
  no-func-assign          : 2
  no-inner-declarations   : [2, "both"]
  no-invalid-regexp       : 2
  no-irregular-whitespace : 2
  no-negated-in-lhs       : 2
  no-obj-calls            : 2
  no-regex-spaces         : 2
  no-sparse-arrays        : 2
  no-unexpected-multiline : 2
  no-unreachable          : 2
  use-isnan               : 2
  valid-jsdoc             : 0
  valid-typeof            : 2

  # Best Practices
  accessor-pairs          : 2
  array-callback-return   : 2
  block-scoped-var        : 2
  complexity              : [0, 10]
  consistent-return       : 2
  curly                   : 1
  default-case            : 2
  dot-location            : [2, "property"]
  dot-notation            : 1
  eqeqeq                  : 2
  guard-for-in            : 2
  no-alert                : 1
  no-caller               : 2
  no-case-declarations    : 0
  no-div-regex            : 2
  no-else-return          : 1
  no-empty-function       : 2
  no-empty-pattern        : 2
  no-eq-null              : 2
  no-eval                 : 2
  no-extend-native        : 2
  no-extra-bind           : 2
  no-extra-label          : 2
  no-fallthrough          : 2
  no-implicit-globals     : 1
  no-floating-decimal     : 1
  no-implicit-coercion    : 0
  no-implied-eval         : 2
  no-invalid-this         : 2
  no-iterator             : 2
  no-labels               : 2
  no-lone-blocks          : 2
  no-loop-func            : 2
  no-magic-numbers        : [0, {
    enforceConst: true
  }]
  no-multi-spaces         : [0, {
    exceptions: {
      "Property"           : true,
      "VariableDeclarator" : true,
      "ImportDeclaration"  : true
    }
  }]
  no-multi-str            : 2
  no-native-reassign      : 2
  no-new-func             : 2
  no-new-wrappers         : 2
  no-new                  : 1
  no-octal-escape         : 2
  no-octal                : 2
  no-param-reassign       : 1
  no-process-env          : 0
  no-proto                : 2
  no-redeclare            : 2
  no-return-assign        : 2
  no-script-url           : 2
  no-self-assign          : 2
  no-self-compare         : 2
  no-sequences            : 2
  no-throw-literal        : 2
  no-unmodified-loop-condition: 2
  no-unused-expressions   : [2, {
    allowShortCircuit: true,
    allowTernary: true
  }]
  no-unused-labels        : 2
  no-useless-call         : 2
  no-useless-concat       : 2
  no-void                 : 2
  no-warning-comments     : 0
  no-with                 : 2
  radix                   : 2
  vars-on-top             : 0
  wrap-iife               : [2, "inside"]
  yoda                    : 2

  # Strict Mode
  strict                  : [2, "never"]

  # Variables
  init-declarations       : [2, "always"]
  no-catch-shadow         : 2
  no-delete-var           : 2
  no-label-var            : 2
  no-shadow-restricted-names : 2
  no-shadow               : [2, {
    builtinGlobals: false,
    hoist         : "all"
  }]
  no-undef-init           : 2
  no-undef                : 1
  no-undefined            : 2
  no-unused-vars          : 2
  no-use-before-define    : [1, "nofunc"]

  # Node.js and CommonJS
  callback-return         : [2,
    ["callback", "cb", "next"]
  ]
  global-require          : 2
  handle-callback-err     : [2, "^(err|error)$"]
  no-mixed-requires       : 0
  no-new-require          : 2
  no-path-concat          : 2
  no-process-exit         : 1
  no-restricted-modules   : 0
  no-sync                 : 0

  # Stylistic Issues
  array-bracket-spacing   : [2, "never"]
  block-spacing           : [2, "always"]
  brace-style             : [2, "1tbs", {
    allowSingleLine: true
  }]
  camelcase               : 0
  comma-spacing           : 2
  comma-style             : [2, "last"]
  computed-property-spacing: 2
  consistent-this         : [2, "self"]
  eol-last                : 2
  func-names              : 0
  func-style              : [2, "expression"]
  id-length               : 0
  id-match                : 0
  indent                  : [2, 2, {
    SwitchCase: 1
  }]
  jsx-quotes              : [2, "prefer-double"]
  key-spacing             : [0, {
    align: "colon"
  }]
  keyword-spacing         : [2, {after: true}]
  lines-around-comment    : [0, {
    beforeBlockComment: false,
    afterBlockComment : false,
    beforeLineComment : false,
    afterLineComment  : false,
    allowBlockStart   : false,
    allowBlockEnd     : false
  }]
  linebreak-style         : [2, "unix"]
  max-nested-callbacks    : [2, 3]
  new-cap                 : [2, {
    properties: false
  }]
  new-parens              : 2
  newline-after-var       : 0
  no-array-constructor    : 2
  no-continue             : 0
  no-inline-comments      : 0
  no-lonely-if            : 2
  no-mixed-spaces-and-tabs: 2
  no-multiple-empty-lines : 2
  no-nested-ternary       : 2
  no-negated-condition    : 2
  no-new-object           : 2
  no-restricted-syntax    : [2, "WithStatement"]
  no-spaced-func          : 2
  no-ternary              : 0
  no-trailing-spaces      : 2
  no-underscore-dangle    : 0
  no-unneeded-ternary     : 2
  object-curly-spacing    : [2, "always"]
  one-var                 : 0
  operator-assignment     : [2, "always"]
  operator-linebreak      : 0
  padded-blocks           : 0
  quote-props             : [2, "as-needed"]
  quotes                  : [2, "single"]
  require-jsdoc           : 1
  semi-spacing            : 2
  semi                    : [2, "always"]
  sort-vars               : 0
  space-before-blocks     : [2, "always"]
  space-before-function-paren: ["error", {
    "anonymous": "always",
    "named": "always",
    "asyncArrow": "ignore"
  }]
  space-in-parens         : [2, "never"]
  space-infix-ops         : 2
  space-unary-ops         : 2
  spaced-comment          : [2, "always"]
  wrap-regex              : 0

  # ECMAScript 6
  arrow-body-style        : [0, "as-needed"]
  arrow-parens            : [2, "always"]
  arrow-spacing           : [2, {
    before: true,
    after: true
  }]
  constructor-super       : 2
  generator-star-spacing  : [2, {
    before: true,
    after : false
  }]
  no-class-assign         : 2
  no-const-assign         : 2
  no-dupe-class-members   : 2
  no-this-before-super    : 2
  no-var                  : 2
  object-shorthand        : [2, "always"]
  prefer-arrow-callback   : 2
  prefer-const            : 2
  prefer-spread           : 2
  prefer-reflect          : 2
  prefer-template         : 2
  require-yield           : 2

  # Legacy
  max-depth               : [2, 5]
  max-len                 : [2, 120, 2]
  max-params              : [2, 7]
  max-statements          : [0, 30]
  no-bitwise              : 1
  no-plusplus             : 0
